name: note
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6
  window_manager: ^0.3.8
  shared_preferences: ^2.2.2
  #rain效果
  parallax_rain: ^1.1.1
  #图标包
  eva_icons_flutter: ^3.1.0
  #主题色
  flex_color_scheme: ^7.3.1
  #动画文本
  animated_text_kit: ^4.2.2
  #唯一id
  uuid: ^4.1.0
  #比较
  equatable: ^2.0.5
  #时间
  intl: ^0.18.1
  #grid_view
  flutter_staggered_grid_view: ^0.7.0
  #数据库
  sqflite: ^2.3.2
  #路径管理
  path_provider: ^2.1.1
  #markdown
  flutter_markdown: ^0.6.22
  # Plugins
  flutter_quill: ^9.3.3
  flutter_quill_extensions: ^9.3.3
  image_cropper: ^5.0.1
  google_fonts: ^6.1.0
  path: ^1.8.3
  #image
  cached_network_image: ^3.3.1
  # For drag and drop feature
  desktop_drop: ^0.4.4
  #to html
  quill_html_converter: ^9.2.14
  #to pdf
  quill_pdf_converter: ^9.2.14
  # For sharing text
  share_plus: ^7.2.2
  pdf: ^3.10.7
  printing: ^5.11.1
  #数据库
  hive: ^2.2.3
  isar_flutter_libs: ^4.0.0-dev.13
  hive_flutter: ^1.1.0
  dartz: ^0.10.1



  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6
  hive_generator: ^2.0.1


  flutter_lints: ^3.0.0


flutter:


  uses-material-design: true

  assets:
    - assets/background/
    - assets/icon/
    #    - assets/RiveAssets/
    #    - assets/language/
    - assets/fonts/
#    - assets/emotion/
  fonts:
    - family: Roboto
      fonts:
       - asset: assets/fonts/Roboto-Italic.ttf
         style: italic

